// Current + historic football and NBA players.
// [sport, name, slug, primary, secondary, era]
export const players = [
  // ── Football — active ──
  ["football", "Lionel Messi", "lionel-messi", "#004D98", "#A50044", "active"],
  ["football", "Cristiano Ronaldo", "cristiano-ronaldo", "#DA291C", "#FFFFFF", "active"],
  ["football", "Kylian Mbappé", "kylian-mbappe", "#004170", "#DA291C", "active"],
  ["football", "Erling Haaland", "erling-haaland", "#6CABDD", "#1C2C5B", "active"],
  ["football", "Kevin De Bruyne", "kevin-de-bruyne", "#6CABDD", "#1C2C5B", "active"],
  ["football", "Mohamed Salah", "mohamed-salah", "#C8102E", "#FBE122", "active"],
  ["football", "Robert Lewandowski", "robert-lewandowski", "#A50044", "#004D98", "active"],
  ["football", "Luka Modrić", "luka-modric", "#FFFFFF", "#FEBE10", "active"],
  ["football", "Neymar", "neymar", "#034694", "#DBA111", "active"],
  ["football", "Karim Benzema", "karim-benzema", "#FFFFFF", "#FEBE10", "active"],
  ["football", "Harry Kane", "harry-kane", "#132257", "#FFFFFF", "active"],
  ["football", "Vinícius Júnior", "vinicius-junior", "#FFFFFF", "#FEBE10", "active"],
  ["football", "Jude Bellingham", "jude-bellingham", "#FFFFFF", "#FEBE10", "active"],
  ["football", "Lamine Yamal", "lamine-yamal", "#A50044", "#004D98", "active"],
  ["football", "Pedri", "pedri", "#A50044", "#004D98", "active"],
  ["football", "Rodri", "rodri", "#6CABDD", "#1C2C5B", "active"],
  ["football", "Cole Palmer", "cole-palmer", "#034694", "#DBA111", "active"],
  ["football", "Bukayo Saka", "bukayo-saka", "#EF0107", "#023474", "active"],
  ["football", "Virgil van Dijk", "virgil-van-dijk", "#C8102E", "#00B2A9", "active"],
  ["football", "Alisson Becker", "alisson-becker", "#C8102E", "#00B2A9", "active"],
  ["football", "Thibaut Courtois", "thibaut-courtois", "#FFFFFF", "#FEBE10", "active"],
  ["football", "Trent Alexander-Arnold", "trent-alexander-arnold", "#C8102E", "#00B2A9", "active"],
  ["football", "Bruno Fernandes", "bruno-fernandes", "#DA291C", "#FBE122", "active"],
  ["football", "Son Heung-min", "son-heung-min", "#132257", "#FFFFFF", "active"],
  ["football", "Phil Foden", "phil-foden", "#6CABDD", "#1C2C5B", "active"],

  // ── Football — historic ──
  ["football", "Pelé", "pele", "#FFCD00", "#009739", "historic"],
  ["football", "Diego Maradona", "diego-maradona", "#75AADB", "#FFFFFF", "historic"],
  ["football", "Johan Cruyff", "johan-cruyff", "#FF6600", "#FFFFFF", "historic"],
  ["football", "Zinedine Zidane", "zinedine-zidane", "#FFFFFF", "#FEBE10", "historic"],
  ["football", "Ronaldinho", "ronaldinho", "#A50044", "#004D98", "historic"],
  ["football", "Ronaldo Nazário", "ronaldo-nazario", "#FFCD00", "#009739", "historic"],
  ["football", "Xavi Hernández", "xavi-hernandez", "#A50044", "#004D98", "historic"],
  ["football", "Andrés Iniesta", "andres-iniesta", "#A50044", "#004D98", "historic"],
  ["football", "Thierry Henry", "thierry-henry", "#EF0107", "#023474", "historic"],
  ["football", "Dennis Bergkamp", "dennis-bergkamp", "#EF0107", "#023474", "historic"],
  ["football", "Kaká", "kaka", "#FFCD00", "#009739", "historic"],
  ["football", "Didier Drogba", "didier-drogba", "#034694", "#DBA111", "historic"],
  ["football", "David Beckham", "david-beckham", "#DA291C", "#FBE122", "historic"],
  ["football", "Wayne Rooney", "wayne-rooney", "#DA291C", "#FBE122", "historic"],
  ["football", "Steven Gerrard", "steven-gerrard", "#C8102E", "#00B2A9", "historic"],
  ["football", "Frank Lampard", "frank-lampard", "#034694", "#DBA111", "historic"],
  ["football", "Paolo Maldini", "paolo-maldini", "#FB090B", "#000000", "historic"],
  ["football", "Gianluigi Buffon", "gianluigi-buffon", "#000000", "#FFFFFF", "historic"],
  ["football", "Cafu", "cafu", "#FFCD00", "#009739", "historic"],
  ["football", "Manuel Neuer", "manuel-neuer", "#DC052D", "#0066B2", "historic"],
  ["football", "Thomas Müller", "thomas-muller", "#DC052D", "#0066B2", "historic"],
  ["football", "Marco van Basten", "marco-van-basten", "#FF6600", "#FFFFFF", "historic"],
  ["football", "Michel Platini", "michel-platini", "#004170", "#DA291C", "historic"],
  ["football", "George Best", "george-best", "#DA291C", "#FBE122", "historic"],
  ["football", "Franz Beckenbauer", "franz-beckenbauer", "#DC052D", "#0066B2", "historic"],
  ["football", "Lev Yashin", "lev-yashin", "#FFD700", "#000000", "historic"],
  ["football", "Ferenc Puskás", "ferenc-puskas", "#FFFFFF", "#FEBE10", "historic"],
  ["football", "Eusébio", "eusebio", "#006600", "#FF0000", "historic"],
  ["football", "Luis Suárez", "luis-suarez", "#A50044", "#004D98", "historic"],
  ["football", "Sergio Ramos", "sergio-ramos", "#FFFFFF", "#FEBE10", "historic"],

  // ── NBA — active ──
  ["nba", "LeBron James", "lebron-james", "#552583", "#FDB927", "active"],
  ["nba", "Stephen Curry", "stephen-curry", "#1D428A", "#FFC72C", "active"],
  ["nba", "Kevin Durant", "kevin-durant", "#007AC1", "#EF3B24", "active"],
  ["nba", "Giannis Antetokounmpo", "giannis-antetokounmpo", "#00471B", "#EEE1C6", "active"],
  ["nba", "Nikola Jokić", "nikola-jokic", "#0E2240", "#FEC524", "active"],
  ["nba", "Luka Dončić", "luka-doncic", "#00538C", "#002B5E", "active"],
  ["nba", "Jayson Tatum", "jayson-tatum", "#007A33", "#BA9653", "active"],
  ["nba", "Joel Embiid", "joel-embiid", "#006BB6", "#ED174C", "active"],
  ["nba", "Kawhi Leonard", "kawhi-leonard", "#C8102E", "#1D428A", "active"],
  ["nba", "Anthony Edwards", "anthony-edwards", "#0C2340", "#236192", "active"],
  ["nba", "Victor Wembanyama", "victor-wembanyama", "#000000", "#C4CED4", "active"],
  ["nba", "Tyrese Haliburton", "tyrese-haliburton", "#002D62", "#FDBB30", "active"],
  ["nba", "Shai Gilgeous-Alexander", "shai-gilgeous-alexander", "#007AC1", "#EF3B24", "active"],
  ["nba", "Devin Booker", "devin-booker", "#1D1160", "#E56020", "active"],
  ["nba", "Ja Morant", "ja-morant", "#5D76A9", "#12173F", "active"],
  ["nba", "Damian Lillard", "damian-lillard", "#E03A3E", "#000000", "active"],
  ["nba", "Jimmy Butler", "jimmy-butler", "#98002E", "#F9A01B", "active"],
  ["nba", "Anthony Davis", "anthony-davis", "#552583", "#FDB927", "active"],
  ["nba", "Trae Young", "trae-young", "#E03A3E", "#C1D32F", "active"],
  ["nba", "Donovan Mitchell", "donovan-mitchell", "#860038", "#FDBB30", "active"],
  ["nba", "Paolo Banchero", "paolo-banchero", "#0077C0", "#C4CED4", "active"],
  ["nba", "Cade Cunningham", "cade-cunningham", "#C8102E", "#1D42BA", "active"],
  ["nba", "Jalen Brunson", "jalen-brunson", "#006BB6", "#F58426", "active"],
  ["nba", "Jaylen Brown", "jaylen-brown", "#007A33", "#BA9653", "active"],
  ["nba", "Bam Adebayo", "bam-adebayo", "#98002E", "#F9A01B", "active"],

  // ── NBA — historic ──
  ["nba", "Michael Jordan", "michael-jordan", "#CE1141", "#000000", "historic"],
  ["nba", "Kobe Bryant", "kobe-bryant", "#552583", "#FDB927", "historic"],
  ["nba", "Magic Johnson", "magic-johnson", "#552583", "#FDB927", "historic"],
  ["nba", "Larry Bird", "larry-bird", "#007A33", "#BA9653", "historic"],
  ["nba", "Kareem Abdul-Jabbar", "kareem-abdul-jabbar", "#552583", "#FDB927", "historic"],
  ["nba", "Wilt Chamberlain", "wilt-chamberlain", "#006BB6", "#ED174C", "historic"],
  ["nba", "Bill Russell", "bill-russell", "#007A33", "#BA9653", "historic"],
  ["nba", "Shaquille O'Neal", "shaquille-oneal", "#552583", "#FDB927", "historic"],
  ["nba", "Tim Duncan", "tim-duncan", "#000000", "#C4CED4", "historic"],
  ["nba", "Hakeem Olajuwon", "hakeem-olajuwon", "#CE1141", "#000000", "historic"],
  ["nba", "Allen Iverson", "allen-iverson", "#006BB6", "#ED174C", "historic"],
  ["nba", "Steve Nash", "steve-nash", "#1D1160", "#E56020", "historic"],
  ["nba", "Dirk Nowitzki", "dirk-nowitzki", "#00538C", "#002B5E", "historic"],
  ["nba", "Karl Malone", "karl-malone", "#002B5C", "#F9A01B", "historic"],
  ["nba", "John Stockton", "john-stockton", "#002B5C", "#F9A01B", "historic"],
  ["nba", "Isiah Thomas", "isiah-thomas", "#C8102E", "#1D42BA", "historic"],
  ["nba", "Charles Barkley", "charles-barkley", "#1D1160", "#E56020", "historic"],
  ["nba", "Patrick Ewing", "patrick-ewing", "#006BB6", "#F58426", "historic"],
  ["nba", "Dwyane Wade", "dwyane-wade", "#98002E", "#F9A01B", "historic"],
  ["nba", "Kevin Garnett", "kevin-garnett", "#0C2340", "#236192", "historic"],
  ["nba", "Paul Pierce", "paul-pierce", "#007A33", "#BA9653", "historic"],
  ["nba", "Ray Allen", "ray-allen", "#007A33", "#BA9653", "historic"],
  ["nba", "Reggie Miller", "reggie-miller", "#002D62", "#FDBB30", "historic"],
  ["nba", "Oscar Robertson", "oscar-robertson", "#002B5C", "#F9A01B", "historic"],
  ["nba", "Jerry West", "jerry-west", "#552583", "#FDB927", "historic"],
  ["nba", "Elgin Baylor", "elgin-baylor", "#552583", "#FDB927", "historic"],
  ["nba", "Scottie Pippen", "scottie-pippen", "#CE1141", "#000000", "historic"],
  ["nba", "Dennis Rodman", "dennis-rodman", "#CE1141", "#000000", "historic"],
  ["nba", "Derrick Rose", "derrick-rose", "#CE1141", "#000000", "historic"],
  ["nba", "Russell Westbrook", "russell-westbrook", "#007AC1", "#EF3B24", "historic"],
];
