// Seed corpus: football (soccer) -> NBA club pairs + multi-sport stars.
// People roster lives in supabase/seed/ — run gen-seed-sql.mjs after edits.

export { sports, people } from "./seed/index.mjs";
export { clubs as entities } from "./seed/clubs.mjs";

// a, b, verdict, { pedigree, trajectory, fanbase, city, aura, style }
export const comparisons = [
  ["arsenal", "boston-celtics",
    "Old money, self-serious, and finally young and good again.",
    {
      pedigree: "Most-decorated old-money institution in the league, identity over flash.",
      trajectory: "Came through a long painful rebuild, now a young elite core that's finally arrived.",
      fanbase: "Demanding, self-serious, convinced of their own sophistication.",
      city: "Cosmopolitan capital, knows it's a big deal.",
      aura: "Expectation is the air they breathe.",
      style: "Structured, principled, occasionally too clever for its own good.",
    }],
  ["manchester-united", "la-lakers",
    "The biggest badge in the sport, currently worn by the wrong team.",
    {
      pedigree: "The biggest brand and the most glamour, titles as a birthright.",
      trajectory: "Coasting on reputation while the product flails.",
      fanbase: "Global, frontrunner-heavy, allergic to mid-table.",
      city: "Industrial roots, showbiz self-image.",
      aura: "Expects to win because of the badge, not the team.",
      style: "Signs names, not systems.",
    }],
  ["manchester-city", "golden-state-warriors",
    "The machine that solved the sport and got resented for it.",
    {
      pedigree: "Decades as the noisy neighbour, then a dynasty built in a lab.",
      trajectory: "From punchline to perennial favourite in one ownership change.",
      fanbase: "New arrivals everywhere, old heads who remember the bad years and never let you forget it.",
      city: "Second club of a first-class city that now runs the place.",
      aura: "Wins so routinely it made winning boring — and everyone else furious.",
      style: "Pass-move geometry; the system is the superstar.",
    }],
  ["liverpool", "san-antonio-spurs",
    "Culture as a weapon: the institution outlasts every star.",
    {
      pedigree: "A trophy room built by dynasties, then a long wait that made the next one taste holy.",
      trajectory: "Reloaded around a beloved coach's system and kept competing after he left.",
      fanbase: "Evangelical, communal, will tell you about the good old days unprompted.",
      city: "Port city with a chip on its shoulder and a song for everything.",
      aura: "Big European nights are their natural habitat.",
      style: "Relentless collective pressing — eleven players, one organism.",
    }],
  ["chelsea", "brooklyn-nets",
    "New money bought a seat at the table, then set the table on fire.",
    {
      pedigree: "History before the takeover is a pub-quiz question; everything real is post-money.",
      trajectory: "Superteam, blow it up, superteam again — chaos as a business model.",
      fanbase: "Loud in the good years, mysteriously quiet otherwise.",
      city: "Glamour postcode in a city that supports someone else.",
      aura: "Menace without warmth; even the trophies feel transactional.",
      style: "A billion pounds of talent searching for an idea.",
    }],
  ["tottenham", "phoenix-suns",
    "Beautiful, doomed, and always one piece away.",
    {
      pedigree: "A proud history of style points and a trophy cabinet on a diet.",
      trajectory: "Periodically brilliant, structurally cursed; the rebuild is always next season.",
      fanbase: "Gallows humour as a love language.",
      city: "Big-market team with small-trophy energy.",
      aura: "The banter era never truly ends, it just changes manager.",
      style: "Front-foot and watchable right up until it matters.",
    }],
  ["newcastle", "okc-thunder",
    "One-club city, deafening building, young and dangerous again.",
    {
      pedigree: "Decades of devotion with shockingly little silver to show for it.",
      trajectory: "New regime, smart spending, a young side nobody wants to visit.",
      fanbase: "The whole city in one stadium; religious attendance, zero irony.",
      city: "The team IS the town. There is no second subject of conversation.",
      aura: "Cold night, hostile crowd, good luck.",
      style: "Run harder than you, want it more than you.",
    }],
  ["west-ham", "ny-knicks",
    "Self-mythologising sufferers from the big city's honest borough.",
    {
      pedigree: "More folklore than trophies, and the folklore does heavy lifting.",
      trajectory: "Every false dawn is greeted like a coronation.",
      fanbase: "Loyalty measured in decades of disappointment; leaving is not an option.",
      city: "The working man's club in a city of glamour postcodes.",
      aura: "Capable of ruining anyone's season except their own.",
      style: "Honest graft with occasional moments of unreasonable beauty.",
    }],
  ["everton", "sacramento-kings",
    "Grand old institution, modern-era cautionary tale.",
    {
      pedigree: "Founding-member royalty; the history is real even if the memory is fading.",
      trajectory: "Mismanaged for a generation; survival celebrated like silverware.",
      fanbase: "Unreasonably loyal, comprehensively suffering, weirdly proud of both.",
      city: "The blue half of a two-club town that the world associates with red.",
      aura: "Doom, interrupted by one cathartic night a season.",
      style: "Whatever keeps them up this year.",
    }],
  ["leeds", "philadelphia-76ers",
    "Everyone hates us and we genuinely do not care.",
    {
      pedigree: "A champion's history wrapped in two decades of wilderness.",
      trajectory: "Booms, busts, processes trusted and abandoned.",
      fanbase: "Siege mentality as identity; the villain role is worn like a medal.",
      city: "Proud, singular, defines itself against the fancier neighbours.",
      aura: "Chaos follows them and they invite it in.",
      style: "Full-throttle, no handbrake, occasionally no defence.",
    }],
  ["aston-villa", "indiana-pacers",
    "Heartland aristocracy back at the big table.",
    {
      pedigree: "European royalty once, provincial nobility ever since.",
      trajectory: "Patient rebuild, smart coach, suddenly dining with the elite again.",
      fanbase: "Knowledgeable, unflashy, allergic to hype until it's earned.",
      city: "Second city syndrome powering a first-class chip on the shoulder.",
      aura: "Hard to beat at home, easy to underestimate everywhere.",
      style: "Drilled, intelligent, more talented than fashionable.",
    }],
  ["brighton", "houston-rockets",
    "The spreadsheet boys who beat your scouts to everything.",
    {
      pedigree: "No history worth mentioning, which is exactly the point.",
      trajectory: "Buy low, develop, sell high, repeat — climbing while smiling.",
      fanbase: "Pleasantly surprised by everything; the house money never runs out.",
      city: "Seaside outsiders crashing a party they were never invited to.",
      aura: "Zero fear; the model believes, so the team believes.",
      style: "Brave on the ball, designed in a database.",
    }],
  ["crystal-palace", "atlanta-hawks",
    "The league's best atmosphere wrapped around a mid-table certainty.",
    {
      pedigree: "Honours list is short; memory of great escapes is long.",
      trajectory: "Forever consolidating, occasionally thrilling.",
      fanbase: "The ultras are the trophy. Best noise in the league, eagle included.",
      city: "South of the river and proud you've never been.",
      aura: "Will beat a title contender at home then lose to anyone.",
      style: "Streetball wingers in a structured league.",
    }],
  ["fulham", "charlotte-hornets",
    "Everyone's second-favourite team, nobody's threat.",
    {
      pedigree: "Charming, old, and mostly decorative.",
      trajectory: "Up, down, up — pleasant either way.",
      fanbase: "Civilised to a fault; the away end has opinions about the wine.",
      city: "The genteel riverside postcode of a ruthless city.",
      aura: "Dangerous only when you've already booked the points.",
      style: "Tidy, watchable, and rarely scary.",
    }],
  ["wolves", "minnesota-timberwolves",
    "Yes, the name. But the suffering matches too.",
    {
      pedigree: "Genuine golden-era history that predates living memory.",
      trajectory: "Long mediocrity, flashes of contention, never quite the leap.",
      fanbase: "Old gold faithful; expectation permanently set to 'we'll see'.",
      city: "Proud industrial town, overlooked by design.",
      aura: "Capable of one famous night a season.",
      style: "Counter-punching with the occasional worldie.",
    }],
  ["nottingham-forest", "chicago-bulls",
    "The dynasty that history can't stop dining out on.",
    {
      pedigree: "Back-to-back European Cups — a peak so high the climb down took decades.",
      trajectory: "Living museum to a miracle, periodically remembering it's a football club.",
      fanbase: "Two generations raised on stories, one finally watching live again.",
      city: "Mid-sized city, immortal banner years.",
      aura: "The shirts weigh more because of what they once did.",
      style: "Whatever it takes; the brand is the past, the present is survival.",
    }],
  ["bayern-munich", "miami-heat",
    "Institutional ruthlessness dressed as culture.",
    {
      pedigree: "Serial winners who treat the domestic trophy as a formality.",
      trajectory: "Reload, never rebuild. The standard does not dip.",
      fanbase: "Expect excellence, tolerate nothing less, holiday in May.",
      city: "Wealthy, polished, slightly smug — and earned it.",
      aura: "'We are who we are' as an actual operating principle.",
      style: "Professional dismantling; flair optional, control mandatory.",
    }],
  ["real-madrid", "la-lakers",
    "The actual Lakers. United fans can file a complaint.",
    {
      pedigree: "The most decorated team in the sport's biggest competition. The conversation ends there.",
      trajectory: "Eras change, galácticos change, the winning doesn't.",
      fanbase: "Global aristocracy; demands a coronation every spring.",
      city: "Capital-city power club with royal patronage, literally.",
      aura: "Comebacks so routine opponents start losing at the anthem.",
      style: "Stars first, structure later, trophies always.",
    }],
  ["barcelona", "golden-state-warriors",
    "The beautiful system that changed the sport, then maxed out the credit card.",
    {
      pedigree: "An identity so strong it became a philosophy with a trophy problem: too many to count.",
      trajectory: "Golden generation, global worship, financial hangover.",
      fanbase: "Believe the style is the trophy; results are a bonus.",
      city: "More than a club, as they will tell you. Repeatedly.",
      aura: "The ghost of the greatest team ever haunts every current XI.",
      style: "Possession as religion; the pass is the point.",
    }],
  ["borussia-dortmund", "utah-jazz",
    "The loudest wall in sport, the quietest trophy cabinet in May.",
    {
      pedigree: "One immortal era, decades of being the best team that doesn't win it.",
      trajectory: "Develop the wonderkid, sell the wonderkid, repeat.",
      fanbase: "The Yellow Wall is the best thing in the sport that isn't a trophy.",
      city: "Industrial heartland; the club is the city's Sunday best.",
      aura: "Glorious in autumn, heartbreak by spring.",
      style: "Young legs, high tempo, eventual sale.",
    }],
  ["psg", "dallas-mavericks",
    "Bought stars for a decade, won the lot the year they bought a team.",
    {
      pedigree: "Domestic monopoly money; the real prize spent years laughing at them.",
      trajectory: "Galaxy-brain superstar era failed; the kids-and-system era delivered everything.",
      fanbase: "Ultras with genuine edge, wrapped in a luxury-brand bow.",
      city: "Fashion capital, football afterthought no longer.",
      aura: "Used to be the punchline of big nights. Not anymore, and they know it.",
      style: "From front-three vanity project to actual coordinated football.",
    }],
  ["atletico-madrid", "detroit-pistons",
    "The bad boys your dad warned the referee about.",
    {
      pedigree: "Forever third in a two-club country, which made them sharper than both.",
      trajectory: "Built a contender from spite and a back four.",
      fanbase: "Choose suffering over glamour and call it character. Correct, frankly.",
      city: "The working-class answer to the palace up the road.",
      aura: "Nobody enjoys playing them. That's the trophy.",
      style: "Two banks of four and a dark art for every occasion.",
    }],
  ["inter-milan", "la-clippers",
    "The other team in the building, with the inferiority complex to match.",
    {
      pedigree: "Genuinely decorated — and still somehow the second story in their own stadium.",
      trajectory: "Cycles of brilliance and farce, often in the same season.",
      fanbase: "Fatalistic connoisseurs; expect betrayal, celebrate anyway.",
      city: "Shares the cathedral with the glamour brand and resents the seating plan.",
      aura: "'Pazza Inter' — chaos isn't a phase, it's the constitution.",
      style: "Wing-backs, a target man, and at least one inexplicable collapse.",
    }],
  ["as-roma", "portland-trail-blazers",
    "Romantic, loyal, and heartbroken on schedule.",
    {
      pedigree: "One-club legends and near-misses; the museum is mostly feelings.",
      trajectory: "Forever building toward a season that never quite lands.",
      fanbase: "Love so intense it's structurally indistinguishable from grief.",
      city: "Eternal city, eternal wait.",
      aura: "Capable of one European night that justifies a decade.",
      style: "A number 10's daydream interrupted by defensive reality.",
    }],
  ["celtic", "boston-celtics",
    "It's literally the same word. Green, diaspora, and a trophy hoard.",
    {
      pedigree: "Most successful club in their league; the banner count is municipal infrastructure.",
      trajectory: "Domestic dominance on loop; Europe is the annual reality check.",
      fanbase: "Irish diaspora institution; the support is a congregation.",
      city: "One half of the fiercest two-club city in the sport.",
      aura: "At home, in green, in full voice — visiting teams shrink.",
      style: "Front-foot tradition; anything cagey gets booed.",
    }],
  ["arsenal", "golden-state-warriors",
    "Pass-pass-pass purists who turned pretty into points. Fight the Celtics take.",
    {
      pedigree: "Invincible once, insufferable about it forever.",
      trajectory: "Wilderness years of style over substance, then the system finally clicked.",
      fanbase: "Aesthetes who'd rather lose beautifully than win ugly. Recently learned to do both.",
      city: "Global city team with a global brunch-hour audience.",
      aura: "When the passing hums, the result feels inevitable.",
      style: "Choreographed triangles; the extra pass is mandatory.",
    }],
];
