/** Shared utilities for bulk roster imports from open datasets. */

export function slugify(input) {
  return String(input ?? "")
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

export function fullName(first, last) {
  return `${String(first ?? "").trim()} ${String(last ?? "").trim()}`.trim();
}

export function inferEra(lastSeasonOrYear, activeFromYear = 2024) {
  const y = Number(lastSeasonOrYear);
  if (!y || Number.isNaN(y)) return "historic";
  return y >= activeFromYear ? "active" : "historic";
}

export function debutYear(debut) {
  if (!debut) return null;
  const m = String(debut).match(/^(\d{4})/);
  return m ? Number(m[1]) : null;
}

/**
 * Assign slugs + disambiguators for rows with duplicate names within a sport.
 * Mutates rows in place: { name, slug, disambiguator, ... }
 */
export function disambiguateCollisions(rows, { nameKey = "name" } = {}) {
  const byName = new Map();
  for (const row of rows) {
    const key = row[nameKey].toLowerCase();
    if (!byName.has(key)) byName.set(key, []);
    byName.get(key).push(row);
  }

  for (const group of byName.values()) {
    if (group.length === 1) {
      const row = group[0];
      if (!row.slug) row.slug = slugify(row.name);
      continue;
    }
    for (const row of group) {
      const tag =
        row.disambiguator?.trim() ||
        row.team?.trim() ||
        (row.debutYear ? `debut ${row.debutYear}` : null) ||
        (row.lastSeason ? `until ${row.lastSeason}` : null) ||
        "unknown";
      row.disambiguator = tag;
      row.slug = `${slugify(row.name)}-${slugify(tag)}`;
    }
  }

  const slugSeen = new Set();
  for (const row of rows) {
    let slug = row.slug || slugify(row.name);
    let n = 2;
    while (slugSeen.has(slug)) {
      slug = `${row.slug || slugify(row.name)}-${n++}`;
    }
    row.slug = slug;
    slugSeen.add(slug);
  }
}

/** Convert import row → seed person tuple */
export function toPersonRow(
  sport,
  row,
  colors,
  type = "player",
  era = "historic"
) {
  return [
    sport,
    row.name,
    row.slug,
    colors[0],
    colors[1],
    type,
    row.era ?? era,
    row.disambiguator ?? null,
  ];
}

export async function fetchText(url) {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`Fetch failed ${url}: ${res.status}`);
  return res.text();
}

export async function fetchJson(url) {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`Fetch failed ${url}: ${res.status}`);
  return res.json();
}

export async function fetchGzipCsv(url) {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`Fetch failed ${url}: ${res.status}`);
  const buf = await res.arrayBuffer();
  const { gunzipSync } = await import("node:zlib");
  return gunzipSync(Buffer.from(buf)).toString("utf8");
}

/** Minimal CSV parser (handles quoted fields). */
export function parseCsv(text) {
  const lines = text.replace(/\r\n/g, "\n").replace(/\r/g, "\n").split("\n");
  if (!lines.length) return [];
  const headers = splitCsvLine(lines[0]);
  const rows = [];
  for (let i = 1; i < lines.length; i++) {
    if (!lines[i].trim()) continue;
    const vals = splitCsvLine(lines[i]);
    const obj = {};
    headers.forEach((h, j) => {
      obj[h] = vals[j] ?? "";
    });
    rows.push(obj);
  }
  return rows;
}

function splitCsvLine(line) {
  const out = [];
  let cur = "";
  let q = false;
  for (let i = 0; i < line.length; i++) {
    const c = line[i];
    if (c === '"') {
      if (q && line[i + 1] === '"') {
        cur += '"';
        i++;
      } else q = !q;
    } else if (c === "," && !q) {
      out.push(cur);
      cur = "";
    } else cur += c;
  }
  out.push(cur);
  return out;
}

export function writeBulkModule(path, exportName, rows, sourceMeta) {
  import("node:fs").then(({ writeFileSync }) => {
    const content = `// AUTO-GENERATED by supabase/import/build-bulk.mjs\n// Source: ${sourceMeta.source}\n// ${rows.length} rows · ${sourceMeta.generatedAt}\n\nexport const ${exportName} = ${JSON.stringify(rows)};\n`;
    writeFileSync(path, content);
  });
}
