import { person } from "./helpers.mjs";

export const coachPeople = [
  // ── Football — active ──
  person("football", "Pep Guardiola", "pep-guardiola", "#6CABDD", "#1C2C5B", "coach", "active"),
  person("football", "Carlo Ancelotti", "carlo-ancelotti", "#FFFFFF", "#FEBE10", "coach", "active"),
  person("football", "Mikel Arteta", "mikel-arteta", "#EF0107", "#023474", "coach", "active"),
  person("football", "Jose Mourinho", "jose-mourinho", "#003399", "#FFFF00", "coach", "active"),
  person("football", "Antonio Conte", "antonio-conte", "#001489", "#C8102E", "coach", "active"),
  person("football", "Marcelo Bielsa", "marcelo-bielsa", "#0038A8", "#FFFFFF", "coach", "active"),
  person("football", "Xabi Alonso", "xabi-alonso", "#E32221", "#000000", "coach", "active"),
  person("football", "Unai Emery", "unai-emery", "#670E36", "#95BFE5", "coach", "active"),
  person("football", "Ange Postecoglou", "ange-postecoglou", "#132257", "#FFFFFF", "coach", "active"),
  person("football", "Luis Enrique", "luis-enrique", "#004170", "#DA291C", "coach", "active"),
  person("football", "Simone Inzaghi", "simone-inzaghi", "#0066B3", "#221F20", "coach", "active"),
  person("football", "Diego Simeone", "diego-simeone", "#CB3524", "#262E62", "coach", "active"),
  person("football", "Hansi Flick", "hansi-flick", "#A50044", "#004D98", "coach", "active"),
  person("football", "Ruben Amorim", "ruben-amorim", "#DA291C", "#FBE122", "coach", "active"),
  person("football", "Arne Slot", "arne-slot", "#C8102E", "#00B2A9", "coach", "active"),
  person("football", "Thomas Tuchel", "thomas-tuchel", "#FFFFFF", "#CE1144", "coach", "active"),
  person("football", "Enzo Maresca", "enzo-maresca", "#034694", "#DBA111", "coach", "active"),
  person("football", "Roberto De Zerbi", "roberto-de-zerbi", "#009688", "#FFFFFF", "coach", "active"),
  person("football", "Vincent Kompany", "vincent-kompany", "#DC052D", "#0066B2", "coach", "active"),

  // ── Football — historic ──
  person("football", "Sir Alex Ferguson", "sir-alex-ferguson", "#DA291C", "#FBE122", "coach", "historic"),
  person("football", "Arsene Wenger", "arsene-wenger", "#EF0107", "#023474", "coach", "historic"),
  person("football", "Zinedine Zidane", "zinedine-zidane-manager", "#FFFFFF", "#FEBE10", "coach", "historic"),
  person("football", "Jurgen Klopp", "jurgen-klopp", "#C8102E", "#00B2A9", "coach", "historic"),
  person("football", "Rinus Michels", "rinus-michels", "#FF6600", "#FFFFFF", "coach", "historic"),
  person("football", "Arrigo Sacchi", "arrigo-sacchi", "#FB090B", "#000000", "coach", "historic"),
  person("football", "Brian Clough", "brian-clough", "#DD0000", "#FFFFFF", "coach", "historic"),
  person("football", "Bill Shankly", "bill-shankly", "#C8102E", "#00B2A9", "coach", "historic"),
  person("football", "Johan Cruyff", "johan-cruyff-manager", "#A50044", "#004D98", "coach", "historic"),
  person("football", "Marcello Lippi", "marcello-lippi", "#000000", "#FFFFFF", "coach", "historic"),
  person("football", "Ottmar Hitzfeld", "ottmar-hitzfeld", "#DC052D", "#0066B2", "coach", "historic"),
  person("football", "Louis van Gaal", "louis-van-gaal", "#DA291C", "#FBE122", "coach", "historic"),
  person("football", "Rafael Benitez", "rafael-benitez", "#C8102E", "#00B2A9", "coach", "historic"),
  person("football", "Roberto Mancini", "roberto-mancini", "#6CABDD", "#1C2C5B", "coach", "historic"),
  person("football", "Vicente del Bosque", "vicente-del-bosque", "#FFFFFF", "#FEBE10", "coach", "historic"),
  person("football", "Fabio Capello", "fabio-capello", "#FB090B", "#000000", "coach", "historic"),

  // ── NBA — active ──
  person("nba", "Gregg Popovich", "gregg-popovich", "#000000", "#C4CED4", "coach", "active"),
  person("nba", "Steve Kerr", "steve-kerr", "#1D428A", "#FFC72C", "coach", "active"),
  person("nba", "Erik Spoelstra", "erik-spoelstra", "#98002E", "#F9A01B", "coach", "active"),
  person("nba", "Doc Rivers", "doc-rivers", "#00471B", "#EEE1C6", "coach", "active"),
  person("nba", "Tyronn Lue", "tyronn-lue", "#C8102E", "#1D428A", "coach", "active"),
  person("nba", "Ime Udoka", "ime-udoka", "#CE1141", "#000000", "coach", "active"),
  person("nba", "Mark Daigneault", "mark-daigneault", "#007AC1", "#EF3B24", "coach", "active"),
  person("nba", "Joe Mazzulla", "joe-mazzulla", "#007A33", "#BA9653", "coach", "active"),
  person("nba", "Tom Thibodeau", "tom-thibodeau", "#006BB6", "#F58426", "coach", "active"),
  person("nba", "Mike Brown", "mike-brown", "#5A2D81", "#63727A", "coach", "active"),
  person("nba", "Quin Snyder", "quin-snyder", "#E03A3E", "#C1D32F", "coach", "active"),
  person("nba", "Jason Kidd", "jason-kidd", "#00538C", "#B8C4CA", "coach", "active"),
  person("nba", "Chris Finch", "chris-finch", "#0C2340", "#78BE20", "coach", "active"),
  person("nba", "Chauncey Billups", "chauncey-billups", "#E03A3E", "#000000", "coach", "active"),
  person("nba", "Rick Carlisle", "rick-carlisle", "#002D62", "#FDBB30", "coach", "active"),

  // ── NBA — historic ──
  person("nba", "Phil Jackson", "phil-jackson", "#552583", "#FDB927", "coach", "historic"),
  person("nba", "Pat Riley", "pat-riley", "#98002E", "#F9A01B", "coach", "historic"),
  person("nba", "Red Auerbach", "red-auerbach", "#007A33", "#BA9653", "coach", "historic"),
  person("nba", "Chuck Daly", "chuck-daly", "#C8102E", "#1D42BA", "coach", "historic"),
  person("nba", "Jerry Sloan", "jerry-sloan", "#002B5C", "#F9A01B", "coach", "historic"),
  person("nba", "Don Nelson", "don-nelson", "#1D428A", "#FFC72C", "coach", "historic"),
  person("nba", "Rudy Tomjanovich", "rudy-tomjanovich", "#CE1141", "#000000", "coach", "historic"),
  person("nba", "Larry Brown", "larry-brown", "#C8102E", "#1D42BA", "coach", "historic"),
  person("nba", "Lenny Wilkens", "lenny-wilkens", "#00653A", "#FFC72C", "coach", "historic"),
  person("nba", "Red Holzman", "red-holzman", "#006BB6", "#F58426", "coach", "historic"),
  person("nba", "Mike D'Antoni", "mike-dantoni", "#1D1160", "#E56020", "coach", "historic"),
  person("nba", "George Karl", "george-karl", "#0E2240", "#FEC524", "coach", "historic"),
  person("nba", "KC Jones", "kc-jones", "#007A33", "#BA9653", "coach", "historic"),
  person("nba", "Bill Sharman", "bill-sharman", "#552583", "#FDB927", "coach", "historic"),
  person("nba", "Jack Ramsay", "jack-ramsay", "#E03A3E", "#000000", "coach", "historic"),
];
