import { person, sportDefault as c } from "./helpers.mjs";
const [p, s] = c("cricket");

export const cricketPeople = [
  // ── Players — active ──
  person("cricket", "Virat Kohli", "virat-kohli", p, s),
  person("cricket", "Rohit Sharma", "rohit-sharma", p, s),
  person("cricket", "Jasprit Bumrah", "jasprit-bumrah", p, s),
  person("cricket", "Ravindra Jadeja", "ravindra-jadeja", p, s),
  person("cricket", "Shubman Gill", "shubman-gill", p, s),
  person("cricket", "Rishabh Pant", "rishabh-pant", p, s),
  person("cricket", "KL Rahul", "kl-rahul", p, s),
  person("cricket", "Hardik Pandya", "hardik-pandya", p, s),
  person("cricket", "Mohammed Shami", "mohammed-shami", p, s),
  person("cricket", "Ravichandran Ashwin", "ravichandran-ashwin", p, s),
  person("cricket", "Babar Azam", "babar-azam", p, s),
  person("cricket", "Shaheen Afridi", "shaheen-afridi", p, s),
  person("cricket", "Mohammad Rizwan", "mohammad-rizwan", p, s),
  person("cricket", "Joe Root", "joe-root", p, s),
  person("cricket", "Ben Stokes", "ben-stokes", p, s),
  person("cricket", "Jos Buttler", "jos-buttler", p, s),
  person("cricket", "Jofra Archer", "jofra-archer", p, s),
  person("cricket", "Pat Cummins", "pat-cummins", p, s),
  person("cricket", "Steve Smith", "steve-smith", p, s),
  person("cricket", "David Warner", "david-warner", p, s),
  person("cricket", "Mitchell Starc", "mitchell-starc", p, s),
  person("cricket", "Glenn Maxwell", "glenn-maxwell", p, s),
  person("cricket", "Travis Head", "travis-head", p, s),
  person("cricket", "Kane Williamson", "kane-williamson", p, s),
  person("cricket", "Trent Boult", "trent-boult", p, s),
  person("cricket", "Rachin Ravindra", "rachin-ravindra", p, s),
  person("cricket", "Rashid Khan", "rashid-khan", p, s),
  person("cricket", "Heinrich Klaasen", "heinrich-klaasen", p, s),
  person("cricket", "Kagiso Rabada", "kagiso-rabada", p, s),
  person("cricket", "Quinton de Kock", "quinton-de-kock", p, s),
  person("cricket", "Shakib Al Hasan", "shakib-al-hasan", p, s),
  person("cricket", "Nicholas Pooran", "nicholas-pooran", p, s),
  person("cricket", "Andre Russell", "andre-russell", p, s),
  person("cricket", "Jason Holder", "jason-holder", p, s),
  person("cricket", "Devon Conway", "devon-conway", p, s),

  // ── Players — historic ──
  person("cricket", "Sachin Tendulkar", "sachin-tendulkar", p, s, "player", "historic"),
  person("cricket", "Rahul Dravid", "rahul-dravid", p, s, "player", "historic"),
  person("cricket", "Virender Sehwag", "virender-sehwag", p, s, "player", "historic"),
  person("cricket", "Anil Kumble", "anil-kumble", p, s, "player", "historic"),
  person("cricket", "Sourav Ganguly", "sourav-ganguly", p, s, "player", "historic"),
  person("cricket", "Kapil Dev", "kapil-dev", p, s, "player", "historic"),
  person("cricket", "Sunil Gavaskar", "sunil-gavaskar", p, s, "player", "historic"),
  person("cricket", "MS Dhoni", "ms-dhoni", p, s, "player", "historic"),
  person("cricket", "Yuvraj Singh", "yuvraj-singh", p, s, "player", "historic"),
  person("cricket", "Brian Lara", "brian-lara", p, s, "player", "historic"),
  person("cricket", "Viv Richards", "viv-richards", p, s, "player", "historic"),
  person("cricket", "Garfield Sobers", "garfield-sobers", p, s, "player", "historic"),
  person("cricket", "Clive Lloyd", "clive-lloyd", p, s, "player", "historic"),
  person("cricket", "Malcolm Marshall", "malcolm-marshall", p, s, "player", "historic"),
  person("cricket", "Curtly Ambrose", "curtly-ambrose", p, s, "player", "historic"),
  person("cricket", "Shane Warne", "shane-warne", p, s, "player", "historic"),
  person("cricket", "Glenn McGrath", "glenn-mcgrath", p, s, "player", "historic"),
  person("cricket", "Ricky Ponting", "ricky-ponting", p, s, "player", "historic"),
  person("cricket", "Adam Gilchrist", "adam-gilchrist", p, s, "player", "historic"),
  person("cricket", "Don Bradman", "don-bradman", p, s, "player", "historic"),
  person("cricket", "Dennis Lillee", "dennis-lillee", p, s, "player", "historic"),
  person("cricket", "Muttiah Muralitharan", "muttiah-muralitharan", p, s, "player", "historic"),
  person("cricket", "Kumar Sangakkara", "kumar-sangakkara", p, s, "player", "historic"),
  person("cricket", "Mahela Jayawardene", "mahela-jayawardene", p, s, "player", "historic"),
  person("cricket", "Sanath Jayasuriya", "sanath-jayasuriya", p, s, "player", "historic"),
  person("cricket", "Wasim Akram", "wasim-akram", p, s, "player", "historic"),
  person("cricket", "Waqar Younis", "waqar-younis", p, s, "player", "historic"),
  person("cricket", "Imran Khan", "imran-khan", p, s, "player", "historic"),
  person("cricket", "Javed Miandad", "javed-miandad", p, s, "player", "historic"),
  person("cricket", "Ian Botham", "ian-botham", p, s, "player", "historic"),
  person("cricket", "Geoffrey Boycott", "geoffrey-boycott", p, s, "player", "historic"),
  person("cricket", "James Anderson", "james-anderson", p, s, "player", "historic"),
  person("cricket", "Stuart Broad", "stuart-broad", p, s, "player", "historic"),
  person("cricket", "Allan Donald", "allan-donald", p, s, "player", "historic"),
  person("cricket", "Jacques Kallis", "jacques-kallis", p, s, "player", "historic"),
  person("cricket", "AB de Villiers", "ab-de-villiers", p, s, "player", "historic"),
  person("cricket", "Dale Steyn", "dale-steyn", p, s, "player", "historic"),
  person("cricket", "Mark Boucher", "mark-boucher", p, s, "player", "historic"),
  person("cricket", "Shane Bond", "shane-bond", p, s, "player", "historic"),
  person("cricket", "Gordon Greenidge", "gordon-greenidge", p, s, "player", "historic"),

  // ── Coaches & managers ──
  person("cricket", "MS Dhoni", "ms-dhoni-coach", p, s, "coach", "active"),
  person("cricket", "Rahul Dravid", "rahul-dravid-coach", p, s, "coach", "active"),
  person("cricket", "Ravi Shastri", "ravi-shastri", p, s, "coach", "historic"),
  person("cricket", "Gary Kirsten", "gary-kirsten", p, s, "coach", "historic"),
  person("cricket", "Andrew Flower", "andrew-flower", p, s, "coach", "historic"),
  person("cricket", "Darren Lehmann", "darren-lehmann", p, s, "coach", "historic"),
  person("cricket", "Justin Langer", "justin-langer", p, s, "coach", "historic"),
  person("cricket", "Trevor Bayliss", "trevor-bayliss", p, s, "coach", "historic"),
  person("cricket", "Mickey Arthur", "mickey-arthur", p, s, "coach", "active"),
  person("cricket", "Geoff Marsh", "geoff-marsh", p, s, "coach", "historic"),
  person("cricket", "John Wright", "john-wright", p, s, "coach", "historic"),
  person("cricket", "Duncan Fletcher", "duncan-fletcher", p, s, "coach", "historic"),
  person("cricket", "Chandika Hathurusingha", "chandika-hathurusingha", p, s, "coach", "active"),
  person("cricket", "Misbah-ul-Haq", "misbah-ul-haq-coach", p, s, "coach", "historic"),
  person("cricket", "Waqar Younis", "waqar-younis-coach", p, s, "coach", "historic"),
  person("cricket", "Brendon McCullum", "brendon-mccullum-coach", p, s, "coach", "active"),
  person("cricket", "Graeme Smith", "graeme-smith-coach", p, s, "coach", "active"),
  person("cricket", "Ottis Gibson", "ottis-gibson", p, s, "coach", "historic"),
  person("cricket", "Mark Boucher", "mark-boucher-coach", p, s, "coach", "active"),
  person("cricket", "Younis Khan", "younis-khan-coach", p, s, "coach", "historic"),
  person("cricket", "John Buchanan", "john-buchanan", p, s, "coach", "historic"),
  person("cricket", "Bob Woolmer", "bob-woolmer", p, s, "coach", "historic"),
  person("cricket", "Ajit Wadekar", "ajit-wadekar", p, s, "coach", "historic"),
  person("cricket", "Anil Kumble", "anil-kumble-coach", p, s, "coach", "historic"),
  person("cricket", "Andy Flower", "andy-flower", p, s, "coach", "historic"),
];
