import { person, sportDefault as c } from "./helpers.mjs";
const [p, s] = c("f1");

export const f1People = [
  // ── Drivers — active ──
  person("f1", "Max Verstappen", "max-verstappen", p, s),
  person("f1", "Lewis Hamilton", "lewis-hamilton", p, s),
  person("f1", "Charles Leclerc", "charles-leclerc", p, s),
  person("f1", "Lando Norris", "lando-norris", p, s),
  person("f1", "Carlos Sainz", "carlos-sainz", p, s),
  person("f1", "George Russell", "george-russell", p, s),
  person("f1", "Oscar Piastri", "oscar-piastri", p, s),
  person("f1", "Fernando Alonso", "fernando-alonso", p, s),
  person("f1", "Sergio Pérez", "sergio-perez", p, s),
  person("f1", "Lance Stroll", "lance-stroll", p, s),
  person("f1", "Pierre Gasly", "pierre-gasly", p, s),
  person("f1", "Esteban Ocon", "esteban-ocon", p, s),
  person("f1", "Yuki Tsunoda", "yuki-tsunoda", p, s),
  person("f1", "Daniel Ricciardo", "daniel-ricciardo", p, s),
  person("f1", "Nico Hülkenberg", "nico-hulkenberg", p, s),
  person("f1", "Kevin Magnussen", "kevin-magnussen", p, s),
  person("f1", "Valtteri Bottas", "valtteri-bottas", p, s),
  person("f1", "Zhou Guanyu", "zhou-guanyu", p, s),
  person("f1", "Alexander Albon", "alexander-albon", p, s),
  person("f1", "Oliver Bearman", "oliver-bearman", p, s),
  person("f1", "Liam Lawson", "liam-lawson", p, s),
  person("f1", "Isack Hadjar", "isack-hadjar", p, s),

  // ── Drivers — historic ──
  person("f1", "Michael Schumacher", "michael-schumacher", p, s, "player", "historic"),
  person("f1", "Ayrton Senna", "ayrton-senna", p, s, "player", "historic"),
  person("f1", "Alain Prost", "alain-prost", p, s, "player", "historic"),
  person("f1", "Juan Manuel Fangio", "juan-manuel-fangio", p, s, "player", "historic"),
  person("f1", "Niki Lauda", "niki-lauda", p, s, "player", "historic"),
  person("f1", "James Hunt", "james-hunt", p, s, "player", "historic"),
  person("f1", "Jackie Stewart", "jackie-stewart", p, s, "player", "historic"),
  person("f1", "Graham Hill", "graham-hill", p, s, "player", "historic"),
  person("f1", "Jim Clark", "jim-clark", p, s, "player", "historic"),
  person("f1", "Stirling Moss", "stirling-moss", p, s, "player", "historic"),
  person("f1", "Nigel Mansell", "nigel-mansell", p, s, "player", "historic"),
  person("f1", "Damon Hill", "damon-hill", p, s, "player", "historic"),
  person("f1", "Mika Häkkinen", "mika-hakkinen", p, s, "player", "historic"),
  person("f1", "Kimi Räikkönen", "kimi-raikkonen", p, s, "player", "historic"),
  person("f1", "Sebastian Vettel", "sebastian-vettel", p, s, "player", "historic"),
  person("f1", "Jenson Button", "jenson-button", p, s, "player", "historic"),
  person("f1", "Nico Rosberg", "nico-rosberg", p, s, "player", "historic"),
  person("f1", "Nelson Piquet", "nelson-piquet", p, s, "player", "historic"),
  person("f1", "Emerson Fittipaldi", "emerson-fittipaldi", p, s, "player", "historic"),
  person("f1", "Gilles Villeneuve", "gilles-villeneuve", p, s, "player", "historic"),
  person("f1", "Jacques Villeneuve", "jacques-villeneuve", p, s, "player", "historic"),
  person("f1", "Mario Andretti", "mario-andretti", p, s, "player", "historic"),
  person("f1", "Keke Rosberg", "keke-rosberg", p, s, "player", "historic"),
  person("f1", "Alberto Ascari", "alberto-ascari", p, s, "player", "historic"),
  person("f1", "Jack Brabham", "jack-brabham", p, s, "player", "historic"),
  person("f1", "Ronnie Peterson", "ronnie-peterson", p, s, "player", "historic"),
  person("f1", "Jochen Rindt", "jochen-rindt", p, s, "player", "historic"),
  person("f1", "Rubens Barrichello", "rubens-barrichello", p, s, "player", "historic"),
  person("f1", "David Coulthard", "david-coulthard", p, s, "player", "historic"),
  person("f1", "Mark Webber", "mark-webber", p, s, "player", "historic"),
  person("f1", "Clay Regazzoni", "clay-regazzoni", p, s, "player", "historic"),
  person("f1", "Carlos Reutemann", "carlos-reutemann", p, s, "player", "historic"),
  person("f1", "Gerhard Berger", "gerhard-berger", p, s, "player", "historic"),

  // ── Team principals & technical figures ──
  person("f1", "Adrian Newey", "adrian-newey", p, s, "coach", "active"),
  person("f1", "Christian Horner", "christian-horner", p, s, "coach", "active"),
  person("f1", "Toto Wolff", "toto-wolff", p, s, "coach", "active"),
  person("f1", "Jean Todt", "jean-todt", p, s, "coach", "historic"),
  person("f1", "Ross Brawn", "ross-brawn", p, s, "coach", "historic"),
  person("f1", "Flavio Briatore", "flavio-briatore", p, s, "coach", "historic"),
  person("f1", "Colin Chapman", "colin-chapman", p, s, "coach", "historic"),
  person("f1", "Frank Williams", "frank-williams", p, s, "coach", "historic"),
  person("f1", "Ron Dennis", "ron-dennis", p, s, "coach", "historic"),
  person("f1", "Mattia Binotto", "mattia-binotto", p, s, "coach", "active"),
  person("f1", "Guenther Steiner", "guenther-steiner", p, s, "coach", "historic"),
  person("f1", "Otmar Szafnauer", "otmar-szafnauer", p, s, "coach", "historic"),
  person("f1", "Andreas Seidl", "andreas-seidl", p, s, "coach", "active"),
  person("f1", "Maurizio Arrivabene", "maurizio-arrivabene", p, s, "coach", "historic"),
  person("f1", "Enzo Ferrari", "enzo-ferrari", p, s, "coach", "historic"),
];
