import { person, sportDefault as c } from "./helpers.mjs";

export const golfPeople = [
  // ── Active ──
  person("golf", "Scottie Scheffler", "scottie-scheffler", ...c("golf"), "player", "active"),
  person("golf", "Rory McIlroy", "rory-mcilroy", ...c("golf"), "player", "active"),
  person("golf", "Jon Rahm", "jon-rahm", ...c("golf"), "player", "active"),
  person("golf", "Jordan Spieth", "jordan-spieth", ...c("golf"), "player", "active"),
  person("golf", "Brooks Koepka", "brooks-koepka", ...c("golf"), "player", "active"),
  person("golf", "Viktor Hovland", "viktor-hovland", ...c("golf"), "player", "active"),
  person("golf", "Xander Schauffele", "xander-schauffele", ...c("golf"), "player", "active"),
  person("golf", "Patrick Cantlay", "patrick-cantlay", ...c("golf"), "player", "active"),
  person("golf", "Collin Morikawa", "collin-morikawa", ...c("golf"), "player", "active"),
  person("golf", "Bryson DeChambeau", "bryson-dechambeau", ...c("golf"), "player", "active"),
  person("golf", "Tommy Fleetwood", "tommy-fleetwood", ...c("golf"), "player", "active"),
  person("golf", "Shane Lowry", "shane-lowry", ...c("golf"), "player", "active"),
  person("golf", "Matt Fitzpatrick", "matt-fitzpatrick", ...c("golf"), "player", "active"),
  person("golf", "Wyndham Clark", "wyndham-clark", ...c("golf"), "player", "active"),
  person("golf", "Ludvig Aberg", "ludvig-aberg", ...c("golf"), "player", "active"),
  person("golf", "Robert MacIntyre", "robert-macintyre", ...c("golf"), "player", "active"),
  person("golf", "Hideki Matsuyama", "hideki-matsuyama", ...c("golf"), "player", "active"),
  person("golf", "Justin Thomas", "justin-thomas", ...c("golf"), "player", "active"),

  // ── Historic ──
  person("golf", "Tiger Woods", "tiger-woods", ...c("golf"), "player", "historic"),
  person("golf", "Jack Nicklaus", "jack-nicklaus", ...c("golf"), "player", "historic"),
  person("golf", "Arnold Palmer", "arnold-palmer", ...c("golf"), "player", "historic"),
  person("golf", "Gary Player", "gary-player", ...c("golf"), "player", "historic"),
  person("golf", "Ben Hogan", "ben-hogan", ...c("golf"), "player", "historic"),
  person("golf", "Sam Snead", "sam-snead", ...c("golf"), "player", "historic"),
  person("golf", "Tom Watson", "tom-watson", ...c("golf"), "player", "historic"),
  person("golf", "Lee Trevino", "lee-trevino", ...c("golf"), "player", "historic"),
  person("golf", "Seve Ballesteros", "seve-ballesteros", ...c("golf"), "player", "historic"),
  person("golf", "Greg Norman", "greg-norman", ...c("golf"), "player", "historic"),
  person("golf", "Phil Mickelson", "phil-mickelson", ...c("golf"), "player", "historic"),
  person("golf", "Ernie Els", "ernie-els", ...c("golf"), "player", "historic"),
  person("golf", "Vijay Singh", "vijay-singh", ...c("golf"), "player", "historic"),
  person("golf", "Fred Couples", "fred-couples", ...c("golf"), "player", "historic"),
  person("golf", "Payne Stewart", "payne-stewart", ...c("golf"), "player", "historic"),
  person("golf", "Nick Faldo", "nick-faldo", ...c("golf"), "player", "historic"),
  person("golf", "Bernhard Langer", "bernhard-langer", ...c("golf"), "player", "historic"),
  person("golf", "Jose Maria Olazabal", "jose-maria-olazabal", ...c("golf"), "player", "historic"),
  person("golf", "Sandy Lyle", "sandy-lyle", ...c("golf"), "player", "historic"),
  person("golf", "Ian Woosnam", "ian-woosnam", ...c("golf"), "player", "historic"),
  person("golf", "Bobby Jones", "bobby-jones", ...c("golf"), "player", "historic"),
  person("golf", "Walter Hagen", "walter-hagen", ...c("golf"), "player", "historic"),
  person("golf", "Byron Nelson", "byron-nelson", ...c("golf"), "player", "historic"),
  person("golf", "Gene Sarazen", "gene-sarazen", ...c("golf"), "player", "historic"),
  person("golf", "Davis Love III", "davis-love-iii", ...c("golf"), "player", "historic"),
  person("golf", "Mark O'Meara", "mark-omeara", ...c("golf"), "player", "historic"),
  person("golf", "Ben Crenshaw", "ben-crenshaw", ...c("golf"), "player", "historic"),
  person("golf", "Curtis Strange", "curtis-strange", ...c("golf"), "player", "historic"),
  person("golf", "Tom Kite", "tom-kite", ...c("golf"), "player", "historic"),
  person("golf", "Hal Sutton", "hal-sutton", ...c("golf"), "player", "historic"),
  person("golf", "Corey Pavin", "corey-pavin", ...c("golf"), "player", "historic"),
  person("golf", "Ray Floyd", "ray-floyd", ...c("golf"), "player", "historic"),
];
