import { person, sportDefault as c } from "./helpers.mjs";

export const mlbPeople = [
  // ── Active — players ──
  person("mlb", "Shohei Ohtani", "shohei-ohtani", ...c("mlb"), "player", "active"),
  person("mlb", "Aaron Judge", "aaron-judge", ...c("mlb"), "player", "active"),
  person("mlb", "Mike Trout", "mike-trout", ...c("mlb"), "player", "active"),
  person("mlb", "Mookie Betts", "mookie-betts", ...c("mlb"), "player", "active"),
  person("mlb", "Ronald Acuña Jr.", "ronald-acuna-jr", ...c("mlb"), "player", "active"),
  person("mlb", "Freddie Freeman", "freddie-freeman", ...c("mlb"), "player", "active"),
  person("mlb", "Juan Soto", "juan-soto", ...c("mlb"), "player", "active"),
  person("mlb", "Bryce Harper", "bryce-harper", ...c("mlb"), "player", "active"),
  person("mlb", "Pete Alonso", "pete-alonso", ...c("mlb"), "player", "active"),
  person("mlb", "Fernando Tatis Jr.", "fernando-tatis-jr", ...c("mlb"), "player", "active"),
  person("mlb", "Francisco Lindor", "francisco-lindor", ...c("mlb"), "player", "active"),
  person("mlb", "Jose Ramirez", "jose-ramirez", ...c("mlb"), "player", "active"),
  person("mlb", "Vladimir Guerrero Jr.", "vladimir-guerrero-jr", ...c("mlb"), "player", "active"),
  person("mlb", "Bobby Witt Jr.", "bobby-witt-jr", ...c("mlb"), "player", "active"),
  person("mlb", "Julio Rodriguez", "julio-rodriguez", ...c("mlb"), "player", "active"),
  person("mlb", "Corbin Burnes", "corbin-burnes", ...c("mlb"), "player", "active"),
  person("mlb", "Gerrit Cole", "gerrit-cole", ...c("mlb"), "player", "active"),
  person("mlb", "Jacob deGrom", "jacob-degrom", ...c("mlb"), "player", "active"),
  person("mlb", "Spencer Strider", "spencer-strider", ...c("mlb"), "player", "active"),
  person("mlb", "Yoshinobu Yamamoto", "yoshinobu-yamamoto", ...c("mlb"), "player", "active"),
  person("mlb", "Yordan Alvarez", "yordan-alvarez", ...c("mlb"), "player", "active"),
  person("mlb", "Austin Riley", "austin-riley", ...c("mlb"), "player", "active"),
  person("mlb", "Cal Raleigh", "cal-raleigh", ...c("mlb"), "player", "active"),
  person("mlb", "Carlos Correa", "carlos-correa", ...c("mlb"), "player", "active"),
  person("mlb", "Kyle Tucker", "kyle-tucker", ...c("mlb"), "player", "active"),
  person("mlb", "Corey Seager", "corey-seager", ...c("mlb"), "player", "active"),
  person("mlb", "Adley Rutschman", "adley-rutschman", ...c("mlb"), "player", "active"),
  person("mlb", "Gunnar Henderson", "gunnar-henderson", ...c("mlb"), "player", "active"),
  person("mlb", "Elly De La Cruz", "elly-de-la-cruz", ...c("mlb"), "player", "active"),
  person("mlb", "Tarik Skubal", "tarik-skubal", ...c("mlb"), "player", "active"),
  person("mlb", "Paul Skenes", "paul-skenes", ...c("mlb"), "player", "active"),
  person("mlb", "Rafael Devers", "rafael-devers", ...c("mlb"), "player", "active"),
  person("mlb", "Jose Altuve", "jose-altuve", ...c("mlb"), "player", "active"),
  person("mlb", "Xander Bogaerts", "xander-bogaerts", ...c("mlb"), "player", "active"),
  person("mlb", "Nolan Arenado", "nolan-arenado", ...c("mlb"), "player", "active"),

  // ── Historic — players ──
  person("mlb", "Babe Ruth", "babe-ruth", ...c("mlb"), "player", "historic"),
  person("mlb", "Willie Mays", "willie-mays", ...c("mlb"), "player", "historic"),
  person("mlb", "Hank Aaron", "hank-aaron", ...c("mlb"), "player", "historic"),
  person("mlb", "Barry Bonds", "barry-bonds", ...c("mlb"), "player", "historic"),
  person("mlb", "Ty Cobb", "ty-cobb", ...c("mlb"), "player", "historic"),
  person("mlb", "Lou Gehrig", "lou-gehrig", ...c("mlb"), "player", "historic"),
  person("mlb", "Ted Williams", "ted-williams", ...c("mlb"), "player", "historic"),
  person("mlb", "Stan Musial", "stan-musial", ...c("mlb"), "player", "historic"),
  person("mlb", "Mickey Mantle", "mickey-mantle", ...c("mlb"), "player", "historic"),
  person("mlb", "Joe DiMaggio", "joe-dimaggio", ...c("mlb"), "player", "historic"),
  person("mlb", "Derek Jeter", "derek-jeter", ...c("mlb"), "player", "historic"),
  person("mlb", "Ken Griffey Jr.", "ken-griffey-jr", ...c("mlb"), "player", "historic"),
  person("mlb", "Cal Ripken Jr.", "cal-ripken-jr", ...c("mlb"), "player", "historic"),
  person("mlb", "Nolan Ryan", "nolan-ryan", ...c("mlb"), "player", "historic"),
  person("mlb", "Sandy Koufax", "sandy-koufax", ...c("mlb"), "player", "historic"),
  person("mlb", "Bob Gibson", "bob-gibson", ...c("mlb"), "player", "historic"),
  person("mlb", "Randy Johnson", "randy-johnson", ...c("mlb"), "player", "historic"),
  person("mlb", "Pedro Martinez", "pedro-martinez", ...c("mlb"), "player", "historic"),
  person("mlb", "Mariano Rivera", "mariano-rivera", ...c("mlb"), "player", "historic"),
  person("mlb", "Ichiro Suzuki", "ichiro-suzuki", ...c("mlb"), "player", "historic"),
  person("mlb", "Albert Pujols", "albert-pujols", ...c("mlb"), "player", "historic"),
  person("mlb", "Miguel Cabrera", "miguel-cabrera", ...c("mlb"), "player", "historic"),
  person("mlb", "Frank Thomas", "frank-thomas", ...c("mlb"), "player", "historic"),
  person("mlb", "Rickey Henderson", "rickey-henderson", ...c("mlb"), "player", "historic"),
  person("mlb", "Roberto Clemente", "roberto-clemente", ...c("mlb"), "player", "historic"),
  person("mlb", "Jackie Robinson", "jackie-robinson", ...c("mlb"), "player", "historic"),
  person("mlb", "Greg Maddux", "greg-maddux", ...c("mlb"), "player", "historic"),
  person("mlb", "Tom Seaver", "tom-seaver", ...c("mlb"), "player", "historic"),
  person("mlb", "Walter Johnson", "walter-johnson", ...c("mlb"), "player", "historic"),
  person("mlb", "Honus Wagner", "honus-wagner", ...c("mlb"), "player", "historic"),

  // ── Active — managers ──
  person("mlb", "Bruce Bochy", "bruce-bochy", ...c("mlb"), "coach", "active"),
  person("mlb", "Terry Francona", "terry-francona", ...c("mlb"), "coach", "active"),
  person("mlb", "Dave Roberts", "dave-roberts", ...c("mlb"), "coach", "active"),
  person("mlb", "Aaron Boone", "aaron-boone", ...c("mlb"), "coach", "active"),
  person("mlb", "Brian Snitker", "brian-snitker", ...c("mlb"), "coach", "active"),
  person("mlb", "Kevin Cash", "kevin-cash", ...c("mlb"), "coach", "active"),
  person("mlb", "Craig Counsell", "craig-counsell", ...c("mlb"), "coach", "active"),
  person("mlb", "Joe Maddon", "joe-maddon", ...c("mlb"), "coach", "active"),

  // ── Historic — managers ──
  person("mlb", "Tony La Russa", "tony-la-russa", ...c("mlb"), "coach", "historic"),
  person("mlb", "Joe Torre", "joe-torre", ...c("mlb"), "coach", "historic"),
  person("mlb", "Casey Stengel", "casey-stengel", ...c("mlb"), "coach", "historic"),
  person("mlb", "John McGraw", "john-mcgraw", ...c("mlb"), "coach", "historic"),
  person("mlb", "Connie Mack", "connie-mack", ...c("mlb"), "coach", "historic"),
  person("mlb", "Sparky Anderson", "sparky-anderson", ...c("mlb"), "coach", "historic"),
  person("mlb", "Tommy Lasorda", "tommy-lasorda", ...c("mlb"), "coach", "historic"),
  person("mlb", "Joe McCarthy", "joe-mccarthy", ...c("mlb"), "coach", "historic"),
  person("mlb", "Walter Alston", "walter-alston", ...c("mlb"), "coach", "historic"),
  person("mlb", "Bobby Cox", "bobby-cox", ...c("mlb"), "coach", "historic"),
  person("mlb", "Earl Weaver", "earl-weaver", ...c("mlb"), "coach", "historic"),
  person("mlb", "Whitey Herzog", "whitey-herzog", ...c("mlb"), "coach", "historic"),
  person("mlb", "Buck Showalter", "buck-showalter", ...c("mlb"), "coach", "historic"),
  person("mlb", "Dusty Baker", "dusty-baker", ...c("mlb"), "coach", "historic"),
  person("mlb", "Jim Leyland", "jim-leyland", ...c("mlb"), "coach", "historic"),
  person("mlb", "Lou Piniella", "lou-piniella", ...c("mlb"), "coach", "historic"),
  person("mlb", "Ned Yost", "ned-yost", ...c("mlb"), "coach", "historic"),
];
