import { person, sportDefault as c } from "./helpers.mjs";

const [p, s] = c("nhl");

export const nhlPeople = [
  // ── Forwards — active ──
  person("nhl", "Connor McDavid", "connor-mcdavid", "#041E42", "#FF4C00", "player", "active"),
  person("nhl", "Nathan MacKinnon", "nathan-mackinnon", "#6F263D", "#236192", "player", "active"),
  person("nhl", "Auston Matthews", "auston-matthews", "#00205B", "#FFFFFF", "player", "active"),
  person("nhl", "David Pastrnak", "david-pastrnak", "#FFB81C", "#000000", "player", "active"),
  person("nhl", "Artemi Panarin", "artemi-panarin", "#0038A8", "#CE1126", "player", "active"),
  person("nhl", "Leon Draisaitl", "leon-draisaitl", "#041E42", "#FF4C00", "player", "active"),
  person("nhl", "Nikita Kucherov", "nikita-kucherov", "#002868", "#FFFFFF", "player", "active"),
  person("nhl", "Matthew Tkachuk", "matthew-tkachuk", "#C8102E", "#041E42", "player", "active"),
  person("nhl", "Jack Hughes", "jack-hughes", "#CE1126", "#000000", "player", "active"),
  person("nhl", "Kirill Kaprizov", "kirill-kaprizov", "#154734", "#A6192E", "player", "active"),
  person("nhl", "Jack Eichel", "jack-eichel", "#B4975A", "#333F42", "player", "active"),
  person("nhl", "Aleksander Barkov", "aleksander-barkov", "#C8102E", "#041E42", "player", "active"),
  person("nhl", "Sebastian Aho", "sebastian-aho", "#CE1126", "#000000", "player", "active"),
  person("nhl", "Mikko Rantanen", "mikko-rantanen", "#6F263D", "#236192", "player", "active"),
  person("nhl", "Filip Forsberg", "filip-forsberg", "#FFB81C", "#041E42", "player", "active"),
  person("nhl", "Jason Robertson", "jason-robertson", "#006847", "#8F8F8C", "player", "active"),
  person("nhl", "Mitch Marner", "mitch-marner", "#00205B", "#FFFFFF", "player", "active"),
  person("nhl", "William Nylander", "william-nylander", "#00205B", "#FFFFFF", "player", "active"),
  person("nhl", "Connor Bedard", "connor-bedard", "#CF0A2C", "#000000", "player", "active"),
  person("nhl", "Sidney Crosby", "sidney-crosby", "#FCB514", "#000000", "player", "active"),
  person("nhl", "Alex Ovechkin", "alex-ovechkin", "#C8102E", "#041E42", "player", "active"),
  person("nhl", "Steven Stamkos", "steven-stamkos", "#002868", "#FFFFFF", "player", "active"),
  person("nhl", "Brad Marchand", "brad-marchand", "#FFB81C", "#000000", "player", "active"),
  // ── Forwards — historic ──
  person("nhl", "Wayne Gretzky", "wayne-gretzky", "#041E42", "#FF4C00", "player", "historic"),
  person("nhl", "Mario Lemieux", "mario-lemieux", "#FCB514", "#000000", "player", "historic"),
  person("nhl", "Gordie Howe", "gordie-howe", "#CE1126", "#FFFFFF", "player", "historic"),
  person("nhl", "Maurice Richard", "maurice-richard", "#AF1E2D", "#192168", "player", "historic"),
  person("nhl", "Jean Beliveau", "jean-beliveau", "#AF1E2D", "#192168", "player", "historic"),
  person("nhl", "Bobby Hull", "bobby-hull", "#CF0A2C", "#000000", "player", "historic"),
  person("nhl", "Guy Lafleur", "guy-lafleur", "#AF1E2D", "#192168", "player", "historic"),
  person("nhl", "Mike Bossy", "mike-bossy", "#00539B", "#F47D30", "player", "historic"),
  person("nhl", "Bryan Trottier", "bryan-trottier", "#00539B", "#F47D30", "player", "historic"),
  person("nhl", "Mark Messier", "mark-messier", "#0038A8", "#CE1126", "player", "historic"),
  person("nhl", "Steve Yzerman", "steve-yzerman", "#CE1126", "#FFFFFF", "player", "historic"),
  person("nhl", "Joe Sakic", "joe-sakic", "#6F263D", "#236192", "player", "historic"),
  person("nhl", "Peter Forsberg", "peter-forsberg", "#6F263D", "#236192", "player", "historic"),
  person("nhl", "Jaromir Jagr", "jaromir-jagr", "#FCB514", "#000000", "player", "historic"),
  person("nhl", "Phil Esposito", "phil-esposito", "#FFB81C", "#000000", "player", "historic"),
  person("nhl", "Marcel Dionne", "marcel-dionne", "#111111", "#A2AAAD", "player", "historic"),
  person("nhl", "Jari Kurri", "jari-kurri", "#041E42", "#FF4C00", "player", "historic"),
  person("nhl", "Teemu Selanne", "teemu-selanne", "#F47A38", "#000000", "player", "historic"),

  // ── Defense — active ──
  person("nhl", "Quinn Hughes", "quinn-hughes", "#00205B", "#00843D", "player", "active"),
  person("nhl", "Cale Makar", "cale-makar", "#6F263D", "#236192", "player", "active"),
  person("nhl", "Victor Hedman", "victor-hedman", "#002868", "#FFFFFF", "player", "active"),
  person("nhl", "Roman Josi", "roman-josi", "#FFB81C", "#041E42", "player", "active"),
  person("nhl", "Adam Fox", "adam-fox", "#0038A8", "#CE1126", "player", "active"),
  person("nhl", "Erik Karlsson", "erik-karlsson", "#FCB514", "#000000", "player", "active"),
  person("nhl", "Miro Heiskanen", "miro-heiskanen", "#006847", "#8F8F8C", "player", "active"),

  // ── Defense — historic ──
  person("nhl", "Bobby Orr", "bobby-orr", "#FFB81C", "#000000", "player", "historic"),
  person("nhl", "Nicklas Lidstrom", "nicklas-lidstrom", "#CE1126", "#FFFFFF", "player", "historic"),
  person("nhl", "Ray Bourque", "ray-bourque", "#FFB81C", "#000000", "player", "historic"),
  person("nhl", "Paul Coffey", "paul-coffey", "#041E42", "#FF4C00", "player", "historic"),
  person("nhl", "Denis Potvin", "denis-potvin", "#00539B", "#F47D30", "player", "historic"),
  person("nhl", "Brian Leetch", "brian-leetch", "#0038A8", "#CE1126", "player", "historic"),
  person("nhl", "Scott Niedermayer", "scott-niedermayer", "#F47A38", "#000000", "player", "historic"),
  person("nhl", "Chris Chelios", "chris-chelios", "#CE1126", "#FFFFFF", "player", "historic"),
  // ── Goaltenders — active ──
  person("nhl", "Igor Shesterkin", "igor-shesterkin", "#0038A8", "#CE1126", "player", "active"),
  person("nhl", "Andrei Vasilevskiy", "andrei-vasilevskiy", "#002868", "#FFFFFF", "player", "active"),
  person("nhl", "Connor Hellebuyck", "connor-hellebuyck", "#041E42", "#004C97", "player", "active"),
  // ── Goaltenders — historic ──
  person("nhl", "Patrick Roy", "patrick-roy", "#AF1E2D", "#192168", "player", "historic"),
  person("nhl", "Martin Brodeur", "martin-brodeur", "#CE1126", "#000000", "player", "historic"),
  person("nhl", "Dominik Hasek", "dominik-hasek", "#002654", "#FCB514", "player", "historic"),
  person("nhl", "Carey Price", "carey-price", "#AF1E2D", "#192168", "player", "historic"),
  person("nhl", "Ken Dryden", "ken-dryden", "#AF1E2D", "#192168", "player", "historic"),
  person("nhl", "Terry Sawchuk", "terry-sawchuk", "#CE1126", "#FFFFFF", "player", "historic"),

  // ── Coaches — active ──
  person("nhl", "Jon Cooper", "jon-cooper", "#002868", "#FFFFFF", "coach", "active"),
  person("nhl", "Sheldon Keefe", "sheldon-keefe", "#00205B", "#FFFFFF", "coach", "active"),
  person("nhl", "Peter Laviolette", "peter-laviolette", "#C8102E", "#041E42", "coach", "active"),
  person("nhl", "Rod Brind'Amour", "rod-brind-amour", "#CE1126", "#000000", "coach", "active"),
  person("nhl", "Rick Tocchet", "rick-tocchet", "#00205B", "#00843D", "coach", "active"),
  person("nhl", "Jim Montgomery", "jim-montgomery", "#FFB81C", "#000000", "coach", "active"),
  person("nhl", "Craig Berube", "craig-berube", "#00205B", "#FFFFFF", "coach", "active"),
  person("nhl", "Jared Bednar", "jared-bednar", "#6F263D", "#236192", "coach", "active"),
  person("nhl", "John Tortorella", "john-tortorella", "#CE1126", "#000000", "coach", "active"),
  person("nhl", "Paul Maurice", "paul-maurice", "#C8102E", "#041E42", "coach", "active"),
  person("nhl", "Mike Sullivan", "mike-sullivan", "#FCB514", "#000000", "coach", "active"),
  person("nhl", "Martin St. Louis", "martin-st-louis", "#AF1E2D", "#192168", "coach", "active"),

  // ── Coaches — historic ──
  person("nhl", "Scotty Bowman", "scotty-bowman", "#CE1126", "#FFFFFF", "coach", "historic"),
  person("nhl", "Joel Quenneville", "joel-quenneville", "#CF0A2C", "#000000", "coach", "historic"),
  person("nhl", "Barry Trotz", "barry-trotz", "#00539B", "#F47D30", "coach", "historic"),
  person("nhl", "Mike Babcock", "mike-babcock", "#00205B", "#FFFFFF", "coach", "historic"),
  person("nhl", "Ken Hitchcock", "ken-hitchcock", "#006847", "#8F8F8C", "coach", "historic"),
  person("nhl", "Darryl Sutter", "darryl-sutter", "#C8102E", "#000000", "coach", "historic"),
  person("nhl", "Randy Carlyle", "randy-carlyle", "#F47A38", "#000000", "coach", "historic"),
  person("nhl", "Rick Bowness", "rick-bowness", "#041E42", "#004C97", "coach", "historic"),
  person("nhl", "Bruce Boudreau", "bruce-boudreau", "#154734", "#A6192E", "coach", "historic"),
  person("nhl", "Pat Burns", "pat-burns", "#AF1E2D", "#192168", "coach", "historic"),
  person("nhl", "Al Arbour", "al-arbour", "#00539B", "#F47D30", "coach", "historic"),
  person("nhl", "Toe Blake", "toe-blake", "#AF1E2D", "#192168", "coach", "historic"),
  person("nhl", "Glen Sather", "glen-sather", "#041E42", "#FF4C00", "coach", "historic"),
];
