import { person, sportDefault as c } from "./helpers.mjs";

export const tennisPeople = [
  // ── Active — men ──
  person("tennis", "Novak Djokovic", "novak-djokovic", ...c("tennis"), "player", "active"),
  person("tennis", "Carlos Alcaraz", "carlos-alcaraz", ...c("tennis"), "player", "active"),
  person("tennis", "Jannik Sinner", "jannik-sinner", ...c("tennis"), "player", "active"),
  person("tennis", "Daniil Medvedev", "daniil-medvedev", ...c("tennis"), "player", "active"),
  person("tennis", "Alexander Zverev", "alexander-zverev", ...c("tennis"), "player", "active"),
  person("tennis", "Andrey Rublev", "andrey-rublev", ...c("tennis"), "player", "active"),
  person("tennis", "Stefanos Tsitsipas", "stefanos-tsitsipas", ...c("tennis"), "player", "active"),
  person("tennis", "Casper Ruud", "casper-ruud", ...c("tennis"), "player", "active"),
  person("tennis", "Taylor Fritz", "taylor-fritz", ...c("tennis"), "player", "active"),
  person("tennis", "Frances Tiafoe", "frances-tiafoe", ...c("tennis"), "player", "active"),
  person("tennis", "Holger Rune", "holger-rune", ...c("tennis"), "player", "active"),
  person("tennis", "Alex de Minaur", "alex-de-minaur", ...c("tennis"), "player", "active"),
  person("tennis", "Tommy Paul", "tommy-paul", ...c("tennis"), "player", "active"),
  person("tennis", "Ben Shelton", "ben-shelton", ...c("tennis"), "player", "active"),
  person("tennis", "Hubert Hurkacz", "hubert-hurkacz", ...c("tennis"), "player", "active"),

  // ── Active — women ──
  person("tennis", "Aryna Sabalenka", "aryna-sabalenka", ...c("tennis"), "player", "active"),
  person("tennis", "Iga Swiatek", "iga-swiatek", ...c("tennis"), "player", "active"),
  person("tennis", "Coco Gauff", "coco-gauff", ...c("tennis"), "player", "active"),
  person("tennis", "Elena Rybakina", "elena-rybakina", ...c("tennis"), "player", "active"),
  person("tennis", "Jessica Pegula", "jessica-pegula", ...c("tennis"), "player", "active"),
  person("tennis", "Qinwen Zheng", "qinwen-zheng", ...c("tennis"), "player", "active"),
  person("tennis", "Ons Jabeur", "ons-jabeur", ...c("tennis"), "player", "active"),
  person("tennis", "Karolina Muchova", "karolina-muchova", ...c("tennis"), "player", "active"),
  person("tennis", "Jasmine Paolini", "jasmine-paolini", ...c("tennis"), "player", "active"),
  person("tennis", "Madison Keys", "madison-keys", ...c("tennis"), "player", "active"),
  person("tennis", "Jelena Ostapenko", "jelena-ostapenko", ...c("tennis"), "player", "active"),
  person("tennis", "Petra Kvitova", "petra-kvitova", ...c("tennis"), "player", "active"),

  // ── Historic — men ──
  person("tennis", "Roger Federer", "roger-federer", ...c("tennis"), "player", "historic"),
  person("tennis", "Rafael Nadal", "rafael-nadal", ...c("tennis"), "player", "historic"),
  person("tennis", "Pete Sampras", "pete-sampras", ...c("tennis"), "player", "historic"),
  person("tennis", "Andre Agassi", "andre-agassi", ...c("tennis"), "player", "historic"),
  person("tennis", "Bjorn Borg", "bjorn-borg", ...c("tennis"), "player", "historic"),
  person("tennis", "John McEnroe", "john-mcenroe", ...c("tennis"), "player", "historic"),
  person("tennis", "Jimmy Connors", "jimmy-connors", ...c("tennis"), "player", "historic"),
  person("tennis", "Rod Laver", "rod-laver", ...c("tennis"), "player", "historic"),
  person("tennis", "Boris Becker", "boris-becker", ...c("tennis"), "player", "historic"),
  person("tennis", "Ivan Lendl", "ivan-lendl", ...c("tennis"), "player", "historic"),
  person("tennis", "Mats Wilander", "mats-wilander", ...c("tennis"), "player", "historic"),
  person("tennis", "Stefan Edberg", "stefan-edberg", ...c("tennis"), "player", "historic"),
  person("tennis", "Andy Murray", "andy-murray", ...c("tennis"), "player", "historic"),
  person("tennis", "Stan Wawrinka", "stan-wawrinka", ...c("tennis"), "player", "historic"),
  person("tennis", "Juan Martin del Potro", "juan-martin-del-potro", ...c("tennis"), "player", "historic"),
  person("tennis", "Andy Roddick", "andy-roddick", ...c("tennis"), "player", "historic"),
  person("tennis", "Lleyton Hewitt", "lleyton-hewitt", ...c("tennis"), "player", "historic"),
  person("tennis", "Gustavo Kuerten", "gustavo-kuerten", ...c("tennis"), "player", "historic"),

  // ── Historic — women ──
  person("tennis", "Serena Williams", "serena-williams", ...c("tennis"), "player", "historic"),
  person("tennis", "Steffi Graf", "steffi-graf", ...c("tennis"), "player", "historic"),
  person("tennis", "Martina Navratilova", "martina-navratilova", ...c("tennis"), "player", "historic"),
  person("tennis", "Chris Evert", "chris-evert", ...c("tennis"), "player", "historic"),
  person("tennis", "Margaret Court", "margaret-court", ...c("tennis"), "player", "historic"),
  person("tennis", "Monica Seles", "monica-seles", ...c("tennis"), "player", "historic"),
  person("tennis", "Maria Sharapova", "maria-sharapova", ...c("tennis"), "player", "historic"),
  person("tennis", "Martina Hingis", "martina-hingis", ...c("tennis"), "player", "historic"),
  person("tennis", "Justine Henin", "justine-henin", ...c("tennis"), "player", "historic"),
  person("tennis", "Kim Clijsters", "kim-clijsters", ...c("tennis"), "player", "historic"),
  person("tennis", "Lindsay Davenport", "lindsay-davenport", ...c("tennis"), "player", "historic"),
  person("tennis", "Amelie Mauresmo", "amelie-mauresmo", ...c("tennis"), "player", "historic"),
  person("tennis", "Venus Williams", "venus-williams", ...c("tennis"), "player", "historic"),
  person("tennis", "Hana Mandlikova", "hana-mandlikova", ...c("tennis"), "player", "historic"),
  person("tennis", "Gabriela Sabatini", "gabriela-sabatini", ...c("tennis"), "player", "historic"),
];
